version: 2
jobs:
  test:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/smira/aptly
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: |
            apt-get update && \
            apt-get install -y python-virtualenv graphviz
      - run:
          name: Install python dependencies
          command: |
              virtualenv system/env
              . system/env/bin/activate
              pip install six packaging appdirs
              pip install -U pip setuptools
              pip install -r system/requirements.txt
      - run:
          name: Show version
          command: make version
      - run:
          name: Preparing test environment
          command: make prepare
      - run:
          name: Running tests
          command: |
            make check 
            make system-test

  build:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/smira/aptly
    steps:
      - checkout
      - run:
          name: Preparing build env
          command: make dev
      - run:
          name: Building
          command: make goxc
      - store_artifacts:
          path: ./xc-out/

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
